/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import javax.swing.*;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ListSelectionModel;
import javax.swing.text.*;

/**
 *
 * @author Thanh‎ Nhut
 */
public class ChatUI extends javax.swing.JFrame {

    String username;
    boolean isBold = false;
    boolean isItalic = false;
    boolean isUnderline = false;

    String currentFont = "Arial";
    int currentSize = 14;
    DefaultListModel<String> userModel = new DefaultListModel<>();

    String currentChatTarget = "Tất cả";

    private Map<String, StringBuilder> chatLogs = new HashMap<>();
    private Map<String, String> lastTimes = new HashMap<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChatUI.class.getName());

    /**
     * Creates new form ChatUI
     */
    public ChatUI(String username) {
        initComponents();
        messagePane.setContentType("text/html");
        messagePane.setText("<html><body></body></html>");
        chatArea.setContentType("text/html");
        this.username = username;

        nameLabel.setText(username);

        // Hiển thị chữ cái đầu làm avatar
        avatarLabel.setText(username.substring(0, 1).toUpperCase());

        startChat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        avatarLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        sendBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        messagePane = new javax.swing.JTextPane();
        formatPanel = new javax.swing.JPanel();
        emojiBtn = new javax.swing.JButton();
        fileBtn = new javax.swing.JButton();
        zipBtn = new javax.swing.JButton();
        italicBtn = new javax.swing.JButton();
        boldBtn = new javax.swing.JButton();
        underlineBtn = new javax.swing.JButton();
        fontBox = new javax.swing.JComboBox<>();
        sizeBox = new javax.swing.JComboBox<>();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextPane();
        userPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("K2D ExtraBold", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("THANH NHỰT");

        avatarLabel.setBackground(new java.awt.Color(102, 204, 255));
        avatarLabel.setFont(new java.awt.Font("K2D Light", 1, 13)); // NOI18N
        avatarLabel.setForeground(new java.awt.Color(255, 255, 255));
        avatarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarLabel.setText("Avatar");
        avatarLabel.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Anton", 3, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 14, 158));
        jLabel1.setText("YEHOO! MESSENGER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setLayout(new java.awt.BorderLayout());

        inputPanel.setLayout(new java.awt.BorderLayout());

        sendBtn.setBackground(new java.awt.Color(114, 14, 158));
        sendBtn.setFont(new java.awt.Font("K2D Light", 1, 13)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("Gửi");
        sendBtn.addActionListener(this::sendBtnActionPerformed);

        jScrollPane3.setViewportView(messagePane);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendBtn)
                .addGap(97, 97, 97))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        formatPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        emojiBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        emojiBtn.setText("🙂");
        emojiBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        emojiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojiBtnMouseClicked(evt);
            }
        });
        emojiBtn.addActionListener(this::emojiBtnActionPerformed);
        formatPanel.add(emojiBtn);

        fileBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        fileBtn.setText("📎");
        fileBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        fileBtn.addActionListener(this::fileBtnActionPerformed);
        formatPanel.add(fileBtn);

        zipBtn.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        zipBtn.setText("📁");
        zipBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        formatPanel.add(zipBtn);

        italicBtn.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        italicBtn.setText("I");
        italicBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        italicBtn.addActionListener(this::italicBtnActionPerformed);
        formatPanel.add(italicBtn);

        boldBtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        boldBtn.setText("B");
        boldBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        boldBtn.addActionListener(this::boldBtnActionPerformed);
        formatPanel.add(boldBtn);

        underlineBtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        underlineBtn.setText("U");
        underlineBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        underlineBtn.addActionListener(this::underlineBtnActionPerformed);
        formatPanel.add(underlineBtn);

        fontBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Tahoma", "Times New Roman", "Segoe UI" }));
        fontBox.addActionListener(this::fontBoxActionPerformed);

        sizeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "24", "28", "32" }));
        sizeBox.addActionListener(this::sizeBoxActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(formatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fontBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fontBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(formatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        inputPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        bottomPanel.add(inputPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(chatArea);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        userPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("K2D Light", 1, 13), new java.awt.Color(114, 14, 158))); // NOI18N
        userPanel.setPreferredSize(new java.awt.Dimension(180, 0));

        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(userList);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        centerPanel.add(userPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        sendMessage();  // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnActionPerformed


    private void underlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underlineBtnActionPerformed
        isUnderline = !isUnderline;
        applyStyle();
        Style style = messagePane.addStyle("Underline", null);
        StyleConstants.setUnderline(style, isUnderline);

        messagePane.setCharacterAttributes(style, false);   // TODO add your handling code here:
    }//GEN-LAST:event_underlineBtnActionPerformed

    private void fontBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontBoxActionPerformed
        currentFont = fontBox.getSelectedItem().toString();
        applyStyle();
        Style style = messagePane.addStyle("Font", null);
        StyleConstants.setFontFamily(style, currentFont);

        messagePane.setCharacterAttributes(style, false);
    }//GEN-LAST:event_fontBoxActionPerformed

    private void boldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldBtnActionPerformed

        isBold = !isBold;
        applyStyle();
        Style style = messagePane.addStyle("Bold", null);
        StyleConstants.setBold(style, isBold);

        messagePane.setCharacterAttributes(style, false);    // TODO add your handling code here:
    }//GEN-LAST:event_boldBtnActionPerformed

    private void italicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicBtnActionPerformed
        isItalic = !isItalic;
        applyStyle();
        Style style = messagePane.addStyle("Italic", null);
        StyleConstants.setItalic(style, isItalic);

        messagePane.setCharacterAttributes(style, false);     // TODO add your handling code here:
    }//GEN-LAST:event_italicBtnActionPerformed

    private void sizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeBoxActionPerformed
        currentSize = Integer.parseInt(sizeBox.getSelectedItem().toString());
        applyStyle();
        Style style = messagePane.addStyle("Size", null);
        StyleConstants.setFontSize(style, currentSize);

        messagePane.setCharacterAttributes(style, false);
    }//GEN-LAST:event_sizeBoxActionPerformed

    private void emojiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emojiBtnActionPerformed
        JPopupMenu menu = new JPopupMenu();

        // cho emoji hiển thị ngang
        menu.setLayout(new java.awt.FlowLayout());

        String[] emojis = {
            "😀", "😁", "😂", "🤣",
            "😍", "😎", "😭", "😡",
            "👍", "❤️", "🔥", "🎉"
        };

        for (String emoji : emojis) {

            JMenuItem item = new JMenuItem(emoji);

            item.setFont(new java.awt.Font("Segoe UI Emoji", java.awt.Font.PLAIN, 18));
            item.setBorder(null);

            item.addActionListener(e -> {
                messagePane.replaceSelection(emoji);
            });

            menu.add(item);
        }

        // hiển thị phía trên nút emoji
        int x = 0;
        int y = -menu.getPreferredSize().height;

        menu.show(emojiBtn, x, y);        // TODO add your handling code here:
    }//GEN-LAST:event_emojiBtnActionPerformed

    private void emojiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emojiBtnMouseClicked

    private void fileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnActionPerformed

        JFileChooser chooser = new JFileChooser();

        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            java.io.File file = chooser.getSelectedFile();

            sendFile(file);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_fileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Client.connect();   // KẾT NỐI SERVER

        java.awt.EventQueue.invokeLater(() -> {
            new ChatUI("TestUser").setVisible(true);
        });

    }

    private void startChat() {

        chatArea.setEditable(false);

        userList.setModel(userModel);

        userModel.addElement("Tất cả");

        userList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        userList.addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {

                String selected = userList.getSelectedValue();

                if (selected != null) {

                    currentChatTarget = selected.replace(" (Bạn)", "");

                    chatArea.setText("<html>"
                            + chatLogs.getOrDefault(
                                    currentChatTarget,
                                    new StringBuilder()
                            ).toString()
                            + "</html>");

                    try {
                        if (!currentChatTarget.equals("Tất cả")) {
                            chatLogs.putIfAbsent(currentChatTarget, new StringBuilder());
                              chatLogs.put(currentChatTarget, new StringBuilder());
lastTimes.remove(currentChatTarget);
                            Client.dos.writeUTF("LOAD_HISTORY|" + currentChatTarget);
                            Client.dos.flush();
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
        userList.setSelectedIndex(0);

        new Thread(this::listenToServer).start();
    }

    private void listenToServer() {

        try {

            while (true) {

                String msg = Client.dis.readUTF();

                if (msg.startsWith("USERS|")) {

                    updateUserList(msg.substring(6));

                } // ===== LOAD LỊCH SỬ CHAT =====
                else if (msg.startsWith("HISTORY|")) {

                    String[] parts = msg.split("\\|", 3);

                    String sender = parts[1];
                    String content = parts[2];

                    String target = sender.equals(username) ? currentChatTarget : sender;

                    appendToLog(target,
                            "<b>" + sender + ":</b>&nbsp;" + content);
                } // ===== CHAT RIÊNG =====
                else if (msg.startsWith("PRIVATE_FROM|")) {

                    String[] parts = msg.split("\\|", 3);

                    String sender = parts[1];

                    String content = parts[2];

                    appendToLog(sender, "<b>" + sender + ":</b>&nbsp;" + content);
                } else if (msg.startsWith("PRIVATE_FILE_FROM|")) {

                    String[] parts = msg.split("\\|");

                    String sender = parts[1];
                    String fileName = parts[2];

                    int fileSize = Client.dis.readInt();

                    byte[] data = new byte[fileSize];

                    Client.dis.readFully(data);

                    java.io.FileOutputStream fos
                            = new java.io.FileOutputStream("downloads_" + fileName);

                    fos.write(data);
                    fos.close();

                    // ghi log đúng phòng chat riêng
                    appendToLog(sender,
                            sender + " đã gửi file riêng: " + fileName);

                } // ===== NHẬN FILE =====
                else if (msg.startsWith("FILE_FROM|")) {

                    String[] parts = msg.split("\\|");

                    String sender = parts[1];
                    String fileName = parts[2];

                    int fileSize = Client.dis.readInt();

                    byte[] data = new byte[fileSize];

                    Client.dis.readFully(data);

                    java.io.FileOutputStream fos
                            = new java.io.FileOutputStream("downloads_" + fileName);

                    fos.write(data);
                    fos.close();

                    appendToLog("Tất cả",
                            sender + " đã gửi file: " + fileName);
                } else if (msg.startsWith("MSG_FROM|")) {

                    String[] parts = msg.split("\\|", 3);

                    String sender = parts[1];
                    String content = parts[2];

                    if (!sender.equals(username)) {
                        appendToLog("Tất cả", "<b>" + sender + ":</b>&nbsp;" + content);
                    }

                } else {

                    // nếu tin nhắn không phải của mình thì mới hiển thị
                    if (!msg.startsWith(username + ":")) {
                        appendToLog("Tất cả", msg);
                    }

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void appendToLog(String targetKey, String message) {

        String time = new java.text.SimpleDateFormat("HH:mm")
                .format(new java.util.Date());

        // nếu chưa có log thì tạo
        chatLogs.putIfAbsent(targetKey, new StringBuilder());

        StringBuilder log = chatLogs.get(targetKey);

        String lastTime = lastTimes.get(targetKey);

        if (!time.equals(lastTime)) {

            log.append("[").append(time).append("]<br>");

            lastTimes.put(targetKey, time);
        }

        if (message.contains("<b>Bạn:</b>")) {
            log.append("<div style='color:#720E9E'>")
                    .append(message)
                    .append("</div>");
        } else {
            log.append(message);
        }

        log.append("<br>");

        if (currentChatTarget.equals(targetKey)) {

            chatArea.setText("<html>" + log.toString() + "</html>");

            chatArea.setCaretPosition(chatArea.getDocument().getLength());
        }
    }

    private void updateUserList(String data) {

        String[] users = data.split(",");

        String currentSelection = userList.getSelectedValue();

        userModel.clear();

        userModel.addElement("Tất cả");

        // thêm chính mình trước
        for (String u : users) {

            if (u.equals(username)) {

                userModel.addElement(u + " (Bạn)");

                chatLogs.putIfAbsent(u, new StringBuilder());
            }
        }

        // thêm các user còn lại
        for (String u : users) {

            if (!u.isEmpty() && !u.equals(username)) {

                userModel.addElement(u);

                chatLogs.putIfAbsent(u, new StringBuilder());
            }
        }

        userList.setSelectedValue(currentSelection, true);
    }

    void sendMessage() {
        try {

            String msg = messagePane.getDocument()
                    .getText(0, messagePane.getDocument().getLength());

            if (msg.trim().isEmpty()) {
                return;
            }

            String style = "";

            if (isBold) {
                style += "font-weight:bold;";
            }
            if (isItalic) {
                style += "font-style:italic;";
            }
            if (isUnderline) {
                style += "text-decoration:underline;";
            }

            style += "font-family:" + currentFont + ";";
            style += "font-size:" + currentSize + "px;";

            msg = "<span style='" + style + "'>" + msg + "</span>";

            messagePane.setText("");

            if (currentChatTarget.equals("Tất cả")) {

                Client.dos.writeUTF("MSG|" + msg);
                Client.dos.flush();

                appendToLog("Tất cả", "<b>Bạn:</b>&nbsp;" + msg);

            } else {

                String target = currentChatTarget.replace(" (Bạn)", "");

                Client.dos.writeUTF("PRIVATE|" + target + "|" + msg);
                Client.dos.flush();

                appendToLog(target, "<b>Bạn:</b>&nbsp;" + msg);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void applyStyle() {

        Style style = messagePane.addStyle("Style", null);

        StyleConstants.setBold(style, isBold);
        StyleConstants.setItalic(style, isItalic);
        StyleConstants.setUnderline(style, isUnderline);
        StyleConstants.setFontFamily(style, currentFont);
        StyleConstants.setFontSize(style, currentSize);

        messagePane.setCharacterAttributes(style, false);
    }

    void sendFile(java.io.File file) {

        try {

            String target = userList.getSelectedValue();

            if (target != null) {
                target = target.replace(" (Bạn)", "");
            }

            String fileName = file.getName();

            byte[] fileBytes = java.nio.file.Files.readAllBytes(file.toPath());

            if (target == null || target.equals("Tất cả")) {

                Client.dos.writeUTF("FILE|" + fileName);
                Client.dos.flush();

                appendToLog("Tất cả",
                        "Bạn đã gửi file: " + fileName);

            } else {

                Client.dos.writeUTF("PRIVATE_FILE|" + target + "|" + fileName);
                Client.dos.flush();

                appendToLog(target,
                        "Bạn đã gửi file riêng: " + fileName);
            }

            Client.dos.writeInt(fileBytes.length);
            Client.dos.write(fileBytes);
            Client.dos.flush();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JButton boldBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextPane chatArea;
    private javax.swing.JButton emojiBtn;
    private javax.swing.JButton fileBtn;
    private javax.swing.JComboBox<String> fontBox;
    private javax.swing.JPanel formatPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton italicBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane messagePane;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton sendBtn;
    private javax.swing.JComboBox<String> sizeBox;
    private javax.swing.JButton underlineBtn;
    private javax.swing.JList<String> userList;
    private javax.swing.JPanel userPanel;
    private javax.swing.JButton zipBtn;
    // End of variables declaration//GEN-END:variables
}
