/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import javax.swing.*;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Thanh‎ Nhut
 */
public class ChatUI extends javax.swing.JFrame {

    String username;

    DefaultListModel<String> userModel = new DefaultListModel<>();

    String currentChatTarget = "Tất cả";

    private Map<String, StringBuilder> chatLogs = new HashMap<>();
    private Map<String, String> lastTimes = new HashMap<>();
    private String lastTime = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChatUI.class.getName());

    /**
     * Creates new form ChatUI
     */
    public ChatUI(String username) {
        initComponents();

        this.username = username;

        nameLabel.setText(username);

        // Hiển thị chữ cái đầu làm avatar
        avatarLabel.setText(username.substring(0, 1).toUpperCase());

        startChat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        avatarLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        messageField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        iconPanel = new javax.swing.JPanel();
        fileBtn = new javax.swing.JButton();
        emojiBtn = new javax.swing.JButton();
        zipBtn = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        userPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("K2D ExtraBold", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("THANH NHỰT");

        avatarLabel.setBackground(new java.awt.Color(102, 204, 255));
        avatarLabel.setFont(new java.awt.Font("K2D Light", 1, 13)); // NOI18N
        avatarLabel.setForeground(new java.awt.Color(255, 255, 255));
        avatarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarLabel.setText("Avatar");
        avatarLabel.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Anton", 3, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 14, 158));
        jLabel1.setText("YEHOO! MESSENGER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setLayout(new java.awt.BorderLayout());

        inputPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        messageField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        messageField.setPreferredSize(new java.awt.Dimension(75, 0));
        messageField.addActionListener(this::messageFieldActionPerformed);

        sendBtn.setBackground(new java.awt.Color(114, 14, 158));
        sendBtn.setFont(new java.awt.Font("K2D Light", 1, 13)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("Gửi");
        sendBtn.addActionListener(this::sendBtnActionPerformed);

        iconPanel.setPreferredSize(new java.awt.Dimension(621, 46));

        fileBtn.setBackground(new java.awt.Color(255, 255, 153));
        fileBtn.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        fileBtn.setText("📎");
        fileBtn.addActionListener(this::fileBtnActionPerformed);

        emojiBtn.setBackground(new java.awt.Color(255, 255, 153));
        emojiBtn.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        emojiBtn.setText("🙂");
        emojiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojiBtnMouseClicked(evt);
            }
        });
        emojiBtn.addActionListener(this::emojiBtnActionPerformed);

        zipBtn.setBackground(new java.awt.Color(255, 255, 153));
        zipBtn.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        zipBtn.setText("📁");

        javax.swing.GroupLayout iconPanelLayout = new javax.swing.GroupLayout(iconPanel);
        iconPanel.setLayout(iconPanelLayout);
        iconPanelLayout.setHorizontalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emojiBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zipBtn)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        iconPanelLayout.setVerticalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emojiBtn)
                    .addComponent(fileBtn)
                    .addComponent(zipBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendBtn))
                            .addComponent(iconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        inputPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        bottomPanel.add(inputPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setLayout(new java.awt.BorderLayout());

        chatArea.setEditable(false);
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        chatArea.setLineWrap(true);
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        userPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("K2D Light", 1, 13), new java.awt.Color(114, 14, 158))); // NOI18N
        userPanel.setPreferredSize(new java.awt.Dimension(180, 0));

        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(userList);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        centerPanel.add(userPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        sendMessage();  // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnActionPerformed

    private void emojiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emojiBtnMouseClicked

    private void emojiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emojiBtnActionPerformed
        JPopupMenu menu = new JPopupMenu();

        // cho emoji hiển thị ngang
        menu.setLayout(new java.awt.FlowLayout());

        String[] emojis = {
            "😀", "😁", "😂", "🤣",
            "😍", "😎", "😭", "😡",
            "👍", "❤️", "🔥", "🎉"
        };

        for (String emoji : emojis) {

            JMenuItem item = new JMenuItem(emoji);

            item.setFont(new java.awt.Font("Segoe UI Emoji", java.awt.Font.PLAIN, 18));
            item.setBorder(null);

            item.addActionListener(e -> {
                messageField.setText(messageField.getText() + emoji);
            });

            menu.add(item);
        }

        // hiển thị phía trên nút emoji
        int x = 0;
        int y = -menu.getPreferredSize().height;

        menu.show(emojiBtn, x, y);        // TODO add your handling code here:
    }//GEN-LAST:event_emojiBtnActionPerformed

    private void fileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnActionPerformed

        JFileChooser chooser = new JFileChooser();

        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            java.io.File file = chooser.getSelectedFile();

            sendFile(file);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_fileBtnActionPerformed

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed
        sendMessage();
        messageField.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_messageFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
            new ChatUI("TestUser").setVisible(true);
        });
    }

    private void startChat() {

        chatArea.setEditable(false);
        chatArea.setLineWrap(true);
        chatArea.setWrapStyleWord(true);

        userList.setModel(userModel);

        userModel.addElement("Tất cả");

        userList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        userList.addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {

                String selected = userList.getSelectedValue();

                if (selected != null) {

                    currentChatTarget = selected.replace(" (Bạn)", "");

                    chatArea.setText(
                            chatLogs.getOrDefault(
                                    currentChatTarget,
                                    new StringBuilder()
                            ).toString()
                    );
                }
            }
        });
        userList.setSelectedIndex(0);

        new Thread(this::listenToServer).start();
    }

    private void listenToServer() {

        try {

            while (true) {

                String msg = Client.dis.readUTF();

                if (msg.startsWith("USERS|")) {

                    updateUserList(msg.substring(6));

                } // ===== CHAT RIÊNG =====
                else if (msg.startsWith("PRIVATE_FROM|")) {

                    String[] parts = msg.split("\\|", 3);

                    String sender = parts[1];

                    String content = parts[2];

                    appendToLog(sender, sender + ": " + content);
                } else if (msg.startsWith("PRIVATE_FILE_FROM|")) {

                    String[] parts = msg.split("\\|");

                    String sender = parts[1];
                    String fileName = parts[2];

                    int fileSize = Client.dis.readInt();

                    byte[] data = new byte[fileSize];

                    Client.dis.readFully(data);

                    java.io.FileOutputStream fos
                            = new java.io.FileOutputStream("downloads_" + fileName);

                    fos.write(data);
                    fos.close();

                    // ghi log đúng phòng chat riêng
                    appendToLog(sender,
                            sender + " đã gửi file riêng: " + fileName);

                } // ===== NHẬN FILE =====
                else if (msg.startsWith("FILE_FROM|")) {

                    String[] parts = msg.split("\\|");

                    String sender = parts[1];
                    String fileName = parts[2];

                    int fileSize = Client.dis.readInt();

                    byte[] data = new byte[fileSize];

                    Client.dis.readFully(data);

                    java.io.FileOutputStream fos
                            = new java.io.FileOutputStream("downloads_" + fileName);

                    fos.write(data);
                    fos.close();

                    appendToLog("Tất cả",
                            sender + " đã gửi file: " + fileName);
                } else if (msg.startsWith("MSG_FROM|")) {

                    String[] parts = msg.split("\\|", 3);

                    String sender = parts[1];
                    String content = parts[2];

                   if (!sender.equals(username)) {
    appendToLog("Tất cả", sender + ": " + content);
}

                } else {

                    // chat tất cả từ server (không có prefix)
                    appendToLog("Tất cả", msg);

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void appendToLog(String targetKey, String message) {

        chatLogs.putIfAbsent(targetKey, new StringBuilder());
        lastTimes.putIfAbsent(targetKey, "");

        String time = new java.text.SimpleDateFormat("HH:mm")
                .format(new java.util.Date());

        StringBuilder log = chatLogs.get(targetKey);

        String lastTime = lastTimes.get(targetKey);

        // nếu phút khác thì hiện thời gian
        if (!time.equals(lastTime)) {

            log.append("[").append(time).append("]\n");

            lastTimes.put(targetKey, time);
        }

        log.append(message).append("\n");

        if (currentChatTarget.equals(targetKey)) {

            chatArea.setText(log.toString());

            chatArea.setCaretPosition(chatArea.getDocument().getLength());
        }
    }

    private void updateUserList(String data) {

        String[] users = data.split(",");

        String currentSelection = userList.getSelectedValue();

        userModel.clear();

        userModel.addElement("Tất cả");

        for (String u : users) {

            if (!u.isEmpty()) {

                String displayName = u;

                // nếu là tài khoản đang đăng nhập
                if (u.equals(username)) {
                    displayName = u + " (Bạn)";
                }

                userModel.addElement(displayName);

                chatLogs.putIfAbsent(u, new StringBuilder());
            }
        }

        userList.setSelectedValue(currentSelection, true);
    }

    void sendMessage() {

        try {

            String msg = messageField.getText().trim();

            if (msg.isEmpty()) {
                return;
            }

            if (currentChatTarget.equals("Tất cả")) {

                Client.dos.writeUTF("MSG|" + msg);
                Client.dos.flush();

                appendToLog("Tất cả", "Bạn: " + msg);

            } else {

                String target = currentChatTarget.replace(" (Bạn)", "");

                Client.dos.writeUTF("PRIVATE|" + target + "|" + msg);
                Client.dos.flush();

                appendToLog(target, "Bạn: " + msg);
            }

            messageField.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void sendFile(java.io.File file) {

        try {

            String target = userList.getSelectedValue();

            if (target != null) {
                target = target.replace(" (Bạn)", "");
            }

            String fileName = file.getName();

            byte[] fileBytes = java.nio.file.Files.readAllBytes(file.toPath());

            if (target == null || target.equals("Tất cả")) {

                Client.dos.writeUTF("FILE|" + fileName);
                Client.dos.flush();

                appendToLog("Tất cả",
                        "Bạn đã gửi file: " + fileName);

            } else {

                Client.dos.writeUTF("PRIVATE_FILE|" + target + "|" + fileName);
                Client.dos.flush();

                appendToLog(target,
                        "Bạn đã gửi file riêng: " + fileName);
            }

            Client.dos.writeInt(fileBytes.length);
            Client.dos.write(fileBytes);
            Client.dos.flush();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JButton emojiBtn;
    private javax.swing.JButton fileBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton sendBtn;
    private javax.swing.JList<String> userList;
    private javax.swing.JPanel userPanel;
    private javax.swing.JButton zipBtn;
    // End of variables declaration//GEN-END:variables
}
